### ISSUE TITLE
Regular expression to match name associated to case.

### ISSUE THREAD

**Issue by codepritesh** [LawSikhoOrg/test_regex_PHP#1]
i am able to filter case number by using reg expression but having problem with matching name .

**Comment by Donnie** [comment]
Hi Pritesh

Well that's what we are testing here. You seem to have figured the first half, now it's your creativity and problem solving skills which will be tested.

Regards,
Donnie

**Comment by codepritesh** [comment]
Hello Donnie sir
i researched a lot regarding this and failed to get a solution. i will get it some solution today i think.
